/**
 * tests/tick_manager.ts
 *
 * WHAT THIS TESTS:
 * Every instruction in tick_manager, in the order they'd be called in production.
 * All tests must pass before Day 2 begins. No exceptions.
 *
 * RUN: anchor test --skip-deploy (after anchor build && anchor deploy)
 * OR:  yarn test tests/tick_manager.ts
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";

// ─── Math helpers (same as sdk/src/tick_math.ts) ──────────────────────────────
// We import directly to keep tests self-contained
import {
  tickToPrice,
  priceToTick,
  nearestUsableTick,
  tickToArrayStartTick,
  arrayStartTickToBitmapIndex,
  bitmapWordAndBit,
  TICK_SPACING,
  TICKS_PER_ARRAY,
} from "../sdk/src/tick_math";

// ─── PDA helpers ──────────────────────────────────────────────────────────────

function getTickArrayPDA(
  programId: PublicKey,
  pool: PublicKey,
  startTick: number
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("tick_array"),
      pool.toBuffer(),
      Buffer.from(new Int32Array([startTick]).buffer),
    ],
    programId
  );
}

function getTickBitmapPDA(
  programId: PublicKey,
  pool: PublicKey,
  wordIndex: number
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("tick_bitmap"),
      pool.toBuffer(),
      Buffer.from(new Int32Array([wordIndex]).buffer),
    ],
    programId
  );
}

function flattenTicks(ticks: unknown[]): any[] {
  return ticks.flatMap((tick) => (Array.isArray(tick) ? tick : [tick]));
}

// ─── Test suite ───────────────────────────────────────────────────────────────

describe("tick_manager", () => {
  // Configure provider
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // We load the program from the workspace
  // Type assertion needed until IDL is generated by `anchor build`
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = anchor.workspace.TickManager as Program<any>;
  const wallet = provider.wallet as anchor.Wallet;

  // Use a fresh pool keypair for each test run (avoids account-already-exists errors)
  const pool = Keypair.generate();
  const ARRAY_SIZE = TICKS_PER_ARRAY * TICK_SPACING; // 88 × 64 = 5632

  // The start tick we'll use in most tests
  const START_TICK = 0; // tick array covering 0 → 5631

  // ─── Math verification tests (no on-chain calls) ────────────────────────────

  describe("Off-chain math (TypeScript)", () => {
    it("tick 0 → price 1.0", () => {
      expect(tickToPrice(0)).to.be.approximately(1.0, 0.000001);
    });

    it("tick 69082 → price ~1000", () => {
      expect(tickToPrice(69082)).to.be.approximately(1000, 0.5);
    });

    it("priceToTick round-trips correctly", () => {
      const testPrices = [1, 10, 100, 150, 200, 1000];
      for (const price of testPrices) {
        const tick = priceToTick(price);
        const recovered = tickToPrice(tick);
        // Should be within one tick of the actual price
        const nextTick = tickToPrice(tick + 1);
        expect(recovered).to.be.at.most(price + 0.001);
        expect(nextTick).to.be.at.least(price - 0.001);
      }
    });

    it("nearestUsableTick rounds down to TICK_SPACING multiples", () => {
      expect(nearestUsableTick(0)).to.equal(0);
      expect(nearestUsableTick(1)).to.equal(0);
      expect(nearestUsableTick(63)).to.equal(0);
      expect(nearestUsableTick(64)).to.equal(64);
      expect(nearestUsableTick(65)).to.equal(64);
      expect(nearestUsableTick(-1)).to.equal(-64);
      expect(nearestUsableTick(-32)).to.equal(-64);
      expect(nearestUsableTick(-64)).to.equal(-64);
    });

    it("tickToArrayStartTick groups correctly", () => {
      expect(tickToArrayStartTick(0)).to.equal(0);
      expect(tickToArrayStartTick(ARRAY_SIZE - 1)).to.equal(0);
      expect(tickToArrayStartTick(ARRAY_SIZE)).to.equal(ARRAY_SIZE);
      expect(tickToArrayStartTick(-1)).to.equal(-ARRAY_SIZE);
      expect(tickToArrayStartTick(-ARRAY_SIZE)).to.equal(-ARRAY_SIZE);
    });

    it("bitmap word and bit calculations", () => {
      const index0 = arrayStartTickToBitmapIndex(0);
      const index1 = arrayStartTickToBitmapIndex(ARRAY_SIZE);
      const { wordIndex: w0, bitIndex: b0 } = bitmapWordAndBit(index0);
      const { wordIndex: w1, bitIndex: b1 } = bitmapWordAndBit(index1);

      expect(index1).to.equal(index0 + 1);
      expect(w1 * 8 + b1).to.equal(w0 * 8 + b0 + 1);
    });
  });

  // ─── On-chain tests ─────────────────────────────────────────────────────────

  describe("On-chain: initialize_tick_array", () => {
    it("initializes a TickArray at tick 0", async () => {
      const [tickArrayPDA] = getTickArrayPDA(
        program.programId,
        pool.publicKey,
        START_TICK
      );

      await program.methods
        .initializeTickArray(START_TICK)
        .accounts({
          tickArray: tickArrayPDA,
          pool: pool.publicKey,
          payer: wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // Fetch and verify account state
      const account = await program.account.tickArray.fetch(tickArrayPDA);
      expect(account.startTickIndex).to.equal(START_TICK);
      expect(account.pool.toString()).to.equal(pool.publicKey.toString());

      // All 88 ticks should be uninitialized
      for (const tick of flattenTicks(account.ticks)) {
        expect(tick.initialized).to.equal(0);
        expect(tick.liquidityGross.toString()).to.equal("0");
      }

      console.log(`  ✓ TickArray created at PDA: ${tickArrayPDA.toString()}`);
    });

    it("rejects non-boundary start tick", async () => {
      const badStartTick = 100; // not a multiple of array_size

      const [badPDA] = getTickArrayPDA(
        program.programId,
        pool.publicKey,
        badStartTick
      );

      try {
        await program.methods
          .initializeTickArray(badStartTick)
          .accounts({
            tickArray: badPDA,
            pool: pool.publicKey,
            payer: wallet.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        expect.fail("Should have thrown InvalidTickSpacing error");
      } catch (err: unknown) {
        expect((err as Error).message).to.include("InvalidTickSpacing");
      }
    });
  });

  describe("On-chain: update_tick (add liquidity at tick boundaries)", () => {
    // Scenario: LP opens position between tick 0 and tick 5632 (full array range)
    // tick 0 is lower bound → liquidity_net = +1000
    // tick 5632 is upper bound → liquidity_net = -1000

    const TICK_LOWER = 0;
    const TICK_UPPER = ARRAY_SIZE; // 5632, needs its own TickArray
    const LIQUIDITY = new BN(1_000_000);

    it("initializes second tick array for upper bound", async () => {
      const [upperArrayPDA] = getTickArrayPDA(
        program.programId,
        pool.publicKey,
        TICK_UPPER
      );

      await program.methods
        .initializeTickArray(TICK_UPPER)
        .accounts({
          tickArray: upperArrayPDA,
          pool: pool.publicKey,
          payer: wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      console.log(`  ✓ Upper TickArray created at tick ${TICK_UPPER}`);
    });

    it("updates lower tick with positive liquidity_net", async () => {
      const [tickArrayPDA] = getTickArrayPDA(
        program.programId,
        pool.publicKey,
        tickToArrayStartTick(TICK_LOWER)
      );

      const arrayIdx = arrayStartTickToBitmapIndex(tickToArrayStartTick(TICK_LOWER));
      const { wordIndex } = bitmapWordAndBit(arrayIdx);
      const [bitmapPDA] = getTickBitmapPDA(
        program.programId,
        pool.publicKey,
        wordIndex
      );

      await program.methods
        .updateTick(
          TICK_LOWER,
          wordIndex,
          LIQUIDITY,          // liquidity_delta = +1,000,000
          false,              // is_upper_tick = false (this is the lower bound)
          new BN(0),          // fee_growth_global_0 (no fees yet)
          new BN(0)           // fee_growth_global_1
        )
        .accounts({
          tickArray: tickArrayPDA,
          tickBitmap: bitmapPDA,
          pool: pool.publicKey,
          authority: wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      const tickArray = await program.account.tickArray.fetch(tickArrayPDA);
      const tick = flattenTicks(tickArray.ticks)[0]; // tick 0 is offset 0 in array starting at 0

      expect(tick.initialized).to.equal(1);
      expect(tick.liquidityGross.toString()).to.equal(LIQUIDITY.toString());
      // liquidity_net = +LIQUIDITY for lower tick
      expect(tick.liquidityNet.toString()).to.equal(LIQUIDITY.toString());

      console.log(`  ✓ Lower tick ${TICK_LOWER}: initialized=true liquidityNet=+${LIQUIDITY}`);
    });

    it("updates upper tick with negative liquidity_net", async () => {
      const [upperArrayPDA] = getTickArrayPDA(
        program.programId,
        pool.publicKey,
        tickToArrayStartTick(TICK_UPPER)
      );

      const arrayIdx = arrayStartTickToBitmapIndex(tickToArrayStartTick(TICK_UPPER));
      const { wordIndex } = bitmapWordAndBit(arrayIdx);
      const [bitmapPDA] = getTickBitmapPDA(
        program.programId,
        pool.publicKey,
        wordIndex
      );

      await program.methods
        .updateTick(
          TICK_UPPER,
          wordIndex,
          LIQUIDITY,          // liquidity_delta
          true,               // is_upper_tick = true (upper bound → net goes negative)
          new BN(0),
          new BN(0)
        )
        .accounts({
          tickArray: upperArrayPDA,
          tickBitmap: bitmapPDA,
          pool: pool.publicKey,
          authority: wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      const tickArray = await program.account.tickArray.fetch(upperArrayPDA);
      const tick = flattenTicks(tickArray.ticks)[0]; // TICK_UPPER is start of its own array

      expect(tick.initialized).to.equal(1);
      // liquidity_net = -LIQUIDITY for upper tick
      const net = tick.liquidityNet as BN;
      expect(net.isNeg()).to.equal(true);
      expect(net.abs().toString()).to.equal(LIQUIDITY.toString());

      console.log(`  ✓ Upper tick ${TICK_UPPER}: initialized=true liquidityNet=-${LIQUIDITY}`);
    });
  });

  describe("On-chain: get_next_initialized_tick", () => {
    it("finds the initialized lower tick when searching downward from above", async () => {
      const [tickArrayPDA] = getTickArrayPDA(
        program.programId,
        pool.publicKey,
        0
      );

      // Search downward from the next usable tick above 0 within the same array.
      // Expected result: tick 0 (the initialized lower boundary we set earlier).
      const result = await program.methods
        .getNextInitializedTick(
          TICK_SPACING,
          true
        )
        .accounts({
          tickArray: tickArrayPDA,
          pool: pool.publicKey,
        })
        .view();

      expect(result).to.equal(0);
      console.log(`  ✓ Next initialized tick below ${TICK_SPACING} = ${result}`);
    });
  });

  describe("On-chain: cross_tick", () => {
    it("crosses the lower tick and returns correct liquidity_net", async () => {
      const [tickArrayPDA] = getTickArrayPDA(
        program.programId,
        pool.publicKey,
        0
      );

      const LIQUIDITY = new BN(1_000_000);

      await program.methods
        .crossTick(
          0,          // tick_index
          new BN(0),  // fee_growth_global_0 (no fees yet)
          new BN(0)   // fee_growth_global_1
        )
        .accounts({
          tickArray: tickArrayPDA,
          pool: pool.publicKey,
          authority: wallet.publicKey,
        })
        .rpc();

      const tickArray = await program.account.tickArray.fetch(tickArrayPDA);
      const tick = flattenTicks(tickArray.ticks)[0];
      expect((tick.liquidityNet as BN).toString()).to.equal(LIQUIDITY.toString());
      expect(tick.feeGrowthOutside0.toString()).to.equal("0");
      expect(tick.feeGrowthOutside1.toString()).to.equal("0");
      console.log(`  ✓ cross_tick(0) preserved liquidity_net = ${tick.liquidityNet}`);
    });
  });
});
