/**
 * scripts/init_pool.ts
 *
 * WHAT THIS DOES:
 * Initialises a SOL/USDC pool on devnet end-to-end:
 *   1. Creates two test token mints (stand-ins for SOL and USDC)
 *   2. Mints test tokens to the wallet
 *   3. Creates a pool at price $150
 *   4. Initialises tick arrays covering the LP range $140–$160
 *   5. Opens an LP position in that range
 *
 * HOW TO RUN:
 *   solana config set --url devnet
 *   solana airdrop 4
 *   anchor build
 *   ./scripts/deploy.sh          # deploy all programs first
 *   npx ts-node scripts/init_pool.ts
 *
 * After this script you have a live pool on devnet.
 * Copy the printed addresses into scripts/demo_swap.ts.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, BN, AnchorProvider } from "@coral-xyz/anchor";
import {
  PublicKey,
  Keypair,
  SystemProgram,
  Connection,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  createMint,
  mintTo,
  getOrCreateAssociatedTokenAccount,
} from "@solana/spl-token";
import * as fs from "fs";
import * as path from "path";

// ─── SDK imports ──────────────────────────────────────────────────────────────

import {
  tickToSqrtPriceQ64,
  priceToTick,
  nearestUsableTick,
  getPoolPDA,
  getVaultPDA,
  fetchPool,
  getPositionPDA,
  getTickArrayPDA,
  getTickBitmapPDA,
  tickToArrayStartTick,
  arrayStartTickToBitmapIndex,
  bitmapWordAndBit,
  fetchPosition,
} from "../sdk/src/index";

// ─── Constants ────────────────────────────────────────────────────────────────

const INITIAL_PRICE  = 150;   // $150
const PRICE_LOWER    = 140;   // LP range lower bound
const PRICE_UPPER    = 160;   // LP range upper bound
const FEE_RATE       = 3_000; // 0.3%
const MINT_DECIMALS  = 6;
const TOKEN0_SUPPLY  = 10_000 * 10 ** MINT_DECIMALS; // 10,000 token0
const TOKEN1_SUPPLY  = 1_500_000 * 10 ** MINT_DECIMALS; // 1.5M token1
const DEPOSIT_AMOUNT_0 = new BN(1_000 * 10 ** MINT_DECIMALS);  // 1,000 token0
const DEPOSIT_AMOUNT_1 = new BN(150_000 * 10 ** MINT_DECIMALS); // 150,000 token1

// ─── Load wallet ──────────────────────────────────────────────────────────────

function loadWallet(): Keypair {
  const walletPath = process.env["WALLET_PATH"]
    ?? path.join(process.env["HOME"] ?? "~", ".config", "solana", "id.json");
  const raw = fs.readFileSync(walletPath, "utf-8");
  return Keypair.fromSecretKey(Buffer.from(JSON.parse(raw)));
}

// ─── Load program IDL ─────────────────────────────────────────────────────────

function loadProgram(
  provider: AnchorProvider,
  programId: PublicKey,
  idlPath: string
): Program {
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf-8")) as anchor.Idl;
  return new Program(idl, programId, provider);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const wallet  = loadWallet();
  const conn    = new Connection("https://api.devnet.solana.com", "confirmed");
  const provider = new AnchorProvider(
    conn,
    new anchor.Wallet(wallet),
    { commitment: "confirmed" }
  );
  anchor.setProvider(provider);

  console.log("\n══════════════════════════════════════════");
  console.log("  NarrowSwap — Pool Initialisation");
  console.log("══════════════════════════════════════════");
  console.log("Wallet:", wallet.publicKey.toString());

  // Check balance
  const balance = await conn.getBalance(wallet.publicKey);
  console.log("Balance:", balance / LAMPORTS_PER_SOL, "SOL");
  if (balance < LAMPORTS_PER_SOL) {
    console.log("Requesting airdrop...");
    const sig = await conn.requestAirdrop(wallet.publicKey, 2 * LAMPORTS_PER_SOL);
    await conn.confirmTransaction(sig);
    console.log("Airdrop confirmed");
  }

  // Load programs from IDL files generated by anchor build
  const tmProgId   = new PublicKey("TickMgr1111111111111111111111111111111111111");
  const poolProgId = new PublicKey("PoolCore1111111111111111111111111111111111111");
  const posMgrId   = new PublicKey("PosMgr11111111111111111111111111111111111111");

  const tmProg   = loadProgram(provider, tmProgId,   "target/idl/tick_manager.json");
  const poolProg = loadProgram(provider, poolProgId, "target/idl/pool_core.json");
  const posMgr   = loadProgram(provider, posMgrId,   "target/idl/position_mgr.json");

  // ── Step 1: Create test token mints ─────────────────────────────────────────

  console.log("\n[1/5] Creating token mints...");
  const mintA = await createMint(conn, wallet, wallet.publicKey, null, MINT_DECIMALS);
  const mintB = await createMint(conn, wallet, wallet.publicKey, null, MINT_DECIMALS);

  // Canonical ordering: mint0 < mint1 by pubkey string
  const [mint0, mint1] = mintA.toBase58() < mintB.toBase58()
    ? [mintA, mintB]
    : [mintB, mintA];
  console.log("  mint0:", mint0.toString());
  console.log("  mint1:", mint1.toString());

  // Create user ATAs and mint tokens
  const ata0 = await getOrCreateAssociatedTokenAccount(conn, wallet, mint0, wallet.publicKey);
  const ata1 = await getOrCreateAssociatedTokenAccount(conn, wallet, mint1, wallet.publicKey);
  await mintTo(conn, wallet, mint0, ata0.address, wallet, TOKEN0_SUPPLY);
  await mintTo(conn, wallet, mint1, ata1.address, wallet, TOKEN1_SUPPLY);
  console.log("  Minted", TOKEN0_SUPPLY / 10 ** MINT_DECIMALS, "token0 to", ata0.address.toString());
  console.log("  Minted", TOKEN1_SUPPLY / 10 ** MINT_DECIMALS, "token1 to", ata1.address.toString());

  // ── Step 2: Initialise pool ──────────────────────────────────────────────────

  console.log("\n[2/5] Initialising pool at price $" + INITIAL_PRICE + "...");
  const initialTick      = nearestUsableTick(priceToTick(INITIAL_PRICE));
  const initialSqrtPrice = new BN(tickToSqrtPriceQ64(initialTick).toString());

  const [poolPubkey] = getPoolPDA(poolProgId, mint0, mint1, FEE_RATE);
  const [vault0]     = getVaultPDA(poolProgId, poolPubkey, 0);
  const [vault1]     = getVaultPDA(poolProgId, poolPubkey, 1);

  await poolProg.methods
    .initializePool(initialSqrtPrice, FEE_RATE, initialTick)
    .accounts({
      pool:               poolPubkey,
      tokenMint0:         mint0,
      tokenMint1:         mint1,
      tokenVault0:        vault0,
      tokenVault1:        vault1,
      tickManagerProgram: tmProgId,
      payer:              wallet.publicKey,
      tokenProgram:       TOKEN_PROGRAM_ID,
      systemProgram:      SystemProgram.programId,
      rent:               anchor.web3.SYSVAR_RENT_PUBKEY,
    })
    .rpc();

  console.log("  Pool:", poolPubkey.toString());
  console.log("  vault0:", vault0.toString());
  console.log("  vault1:", vault1.toString());

  // ── Step 3: Initialise tick arrays ───────────────────────────────────────────

  console.log("\n[3/5] Initialising tick arrays...");
  const tickLower = nearestUsableTick(priceToTick(PRICE_LOWER));
  const tickUpper = nearestUsableTick(priceToTick(PRICE_UPPER));

  const arraysNeeded = [
    ...new Set([
      tickToArrayStartTick(tickLower),
      tickToArrayStartTick(tickUpper),
      tickToArrayStartTick(initialTick),
    ]),
  ];

  for (const startTick of arraysNeeded) {
    const [arrPDA] = getTickArrayPDA(tmProgId, poolPubkey, startTick);
    await tmProg.methods
      .initializeTickArray(startTick)
      .accounts({
        tickArray:     arrPDA,
        pool:          poolPubkey,
        payer:         wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    console.log("  TickArray at tick", startTick, "->", arrPDA.toString());
  }

  // ── Step 4: Open LP position ─────────────────────────────────────────────────

  console.log("\n[4/5] Opening LP position $" + PRICE_LOWER + "-$" + PRICE_UPPER + "...");

  const lowerArrayStart = tickToArrayStartTick(tickLower);
  const upperArrayStart = tickToArrayStartTick(tickUpper);

  const [tickArrayLower]  = getTickArrayPDA(tmProgId, poolPubkey, lowerArrayStart);
  const [tickArrayUpper]  = getTickArrayPDA(tmProgId, poolPubkey, upperArrayStart);

  const lBitmapIdx = arrayStartTickToBitmapIndex(lowerArrayStart);
  const uBitmapIdx = arrayStartTickToBitmapIndex(upperArrayStart);
  const { wordIndex: lWord } = bitmapWordAndBit(lBitmapIdx);
  const { wordIndex: uWord } = bitmapWordAndBit(uBitmapIdx);

  const [tickBitmapLower] = getTickBitmapPDA(tmProgId, poolPubkey, lWord);
  const [tickBitmapUpper] = getTickBitmapPDA(tmProgId, poolPubkey, uWord);

  const nftMintKp = Keypair.generate();
  const [positionPubkey] = getPositionPDA(posMgrId, nftMintKp.publicKey);

  const { getAssociatedTokenAddressSync } = await import("@solana/spl-token");
  const nftAta = getAssociatedTokenAddressSync(nftMintKp.publicKey, wallet.publicKey);

  await posMgr.methods
    .openPosition(
      DEPOSIT_AMOUNT_0,
      DEPOSIT_AMOUNT_1,
      new BN(0),   // min0 (no slippage protection in script — use real values in prod)
      new BN(0),   // min1
      tickLower,
      tickUpper
    )
    .accounts({
      position:               positionPubkey,
      pool:                   poolPubkey,
      tokenVault0:            vault0,
      tokenVault1:            vault1,
      nftMint:                nftMintKp.publicKey,
      nftTokenAccount:        nftAta,
      userTokenAccount0:      ata0.address,
      userTokenAccount1:      ata1.address,
      tickArrayLower,
      tickArrayUpper,
      tickBitmapLower,
      tickBitmapUpper,
      owner:                  wallet.publicKey,
      tickManagerProgram:     tmProgId,
      poolCoreProgram:        poolProgId,
      tokenProgram:           TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      systemProgram:          SystemProgram.programId,
      rent:                   anchor.web3.SYSVAR_RENT_PUBKEY,
    })
    .signers([nftMintKp])
    .rpc();

  const pos  = await fetchPosition(posMgr, positionPubkey);
  const pool = await fetchPool(poolProg, poolPubkey);

  console.log("  Position:", positionPubkey.toString());
  console.log("  NFT mint:", nftMintKp.publicKey.toString());
  console.log("  Liquidity:", pos.liquidity.toString());
  console.log("  Pool liquidity:", pool.liquidity.toString());

  // ── Step 5: Print summary ────────────────────────────────────────────────────

  const explorerBase = "https://explorer.solana.com/address";
  const cluster      = "?cluster=devnet";

  console.log("\n[5/5] DONE. Save these addresses:\n");
  console.log("  POOL_ADDRESS  =", poolPubkey.toString());
  console.log("  MINT_0        =", mint0.toString());
  console.log("  MINT_1        =", mint1.toString());
  console.log("  USER_ATA_0    =", ata0.address.toString());
  console.log("  USER_ATA_1    =", ata1.address.toString());
  console.log("  POSITION      =", positionPubkey.toString());
  console.log("  NFT_MINT      =", nftMintKp.publicKey.toString());
  console.log("\nExplorer links:");
  console.log(" ", explorerBase + "/" + poolPubkey.toString() + cluster);
  console.log(" ", explorerBase + "/" + positionPubkey.toString() + cluster);
  console.log("\n══════════════════════════════════════════\n");
}

main().catch((err: unknown) => {
  console.error("Error:", err);
  process.exit(1);
});